# Generated by Django 5.0.6 on 2024-07-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
